// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace DangDuyHien0230.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230623015013_DDHHocsinhgioi")]
    partial class DDHHocsinhgioi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("DangDuyHien0230.Models.DDHHocsinhgioi", b =>
                {
                    b.Property<string>("Ketqua")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sinhvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ketqua");

                    b.HasIndex("Sinhvien");

                    b.ToTable("DDHHocsinhgioi");
                });

            modelBuilder.Entity("DangDuyHien0230.Models.DDHSinhvien", b =>
                {
                    b.Property<string>("Sinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thanhpho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Truong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sinhvien");

                    b.ToTable("DDHSinhvien");
                });

            modelBuilder.Entity("DangDuyHien0230.Models.DDHHocsinhgioi", b =>
                {
                    b.HasOne("DangDuyHien0230.Models.DDHSinhvien", "DDHSinhvien")
                        .WithMany()
                        .HasForeignKey("Sinhvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DDHSinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
