// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace DangDuyHien0230.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("DangDuyHien0230.Models.DDHSinhvien", b =>
                {
                    b.Property<string>("Sinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thanhpho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Truong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sinhvien");

                    b.ToTable("DDHSinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
